### PR TITLE
Feature/3312 drawer footer api page

### PR DESCRIPTION
**Pull request by bkarambe**
Fixes # BLUI-3312

#### Changes proposed in this Pull Request:
- Added Drawer Footer api docs

#### Screenshots:
Screenshot 2022-07-28 at 4 16 17 PM

#### To Test:
- yarn start:reactdev
- Navigate to Drawer->Drawer Footer->API DOCS (tab)

### CODE REVIEW

**Review by jeffvg — APPROVED** [review]
looks good

**Comment by huayunh** [comment]
Is it possible to style the table like Material Design's style?

https://brightlayer-ui-dev.github.io/patterns/tables#design-specifications

**Comment by daileytj** [comment]
Should the `<components>` be styled like they are in the design or are there very specific places where they get highlighted in a code block?

Screenshot from current demo
Screen Shot 2022-07-28 at 2 17 12 PM

Partial image from design file
Screen Shot 2022-07-28 at 2 17 04 PM

**Comment by bkarambe** [comment]
@huayunh @daileytj Yes, we are going to style tables and components names in the markdown style story [BLUI-3323](https://jira-prod.tcc.etn.com/browse/BLUI-3323)

**Pull request merged**
