### PR TITLE
Playground for Drawer Nav Item

### PR DESCRIPTION
**Pull request by ektasawant**
Fixes 3419 .

#### Changes proposed in this Pull Request:
- Playground for Drawer Nav Item

#### To Test:
- components/drawer/drawer-nav-item/playground

Note: rightComponent prop will handle in example page.

### CODE REVIEW

**Review by huayunh — APPROVED** [review]
Assuming you will have a separate story to add all shared props, this looks good to me

**Comment by ektasawant** [comment]
> 

Do we need sharedProps for navItem? Since all sharedProps are available in Drawer story? I can make small PR for this then.

**Comment by huayunh** [comment]
That was the goal of Shared Props, as they are shared between Drawer, (DrawerBody), DrawerNavGroup and DrawerNavItem.

**Comment by ektasawant** [comment]
> Drawer, (DrawerBody), DrawerNavGroup and DrawerNavItem.

Sure will merge this story and raise and create a story for DrawerBody, DrawerNavGroup and DrawerNavItem (shared props)

**Pull request merged**
