### PR TITLE
Fix/3546 hide empty string from snippet

### PR DESCRIPTION
**Pull request by ektasawant**
Fixes 3546 .

#### Changes proposed in this Pull Request:
Review below component's playground snippet only:

- App Bar
- Channel Value
- Drawer
- Drawer Header
- Drawer Subheader
- Drawer Footer
- Drawer Nav Item
- Drawer Nav Group
- Drawer Rail Item
- Empty State
- Hero
- Info List Item
- Score Card
- Toolbar Menu
- UserMenu

#### To Test:
- Playground and generated snippets of above mentioned components.

### CODE REVIEW

**Review by huayunh — COMMENTED** [review]
When an optional knob field is empty, nothing should show up in the code snippet either.

image

**Comment by huayunh** [comment]
image

**Comment by ektasawant** [comment]
> When an optional knob field is empty, nothing should show up in the code snippet either.
> 
> image

Fixed this for all components.

**Comment by ektasawant** [comment]
> image

Done

**Comment by ektasawant** [comment]
Fixed https://github.com/brightlayer-ui/react-component-library/issues/579

**Comment by huayunh** [comment]
- In app bar, if I try removing `collapsedHeight` or `expandedHeight`, somehow the app bar starts misbehaving
- the `animationDuration` prop does not allow me to clear it — if I attempt to delete everything in the field, it will yield `0`
https://user-images.githubusercontent.com/8997218/194061258-0762d624-a980-4e8e-9c56-e43cda9406ad.mov

**Comment by huayunh** [comment]
> Since animationDuration is expecting a number when we are passing '' it gives an error. So , I added it as 0

When the knob gives a `''`, the dev doc should pass it to the component as `undefined`. This behavior should apply to all optional `number` props

**Comment by emclaug2** [comment]
Any updates w/ this PR?

**Comment by ektasawant** [comment]
> * In app bar, if I try removing `collapsedHeight` or `expandedHeight`, somehow the app bar starts misbehaving
> * the `animationDuration` prop does not allow me to clear it — if I attempt to delete everything in the field, it will yield `0`'
>   
>   * This applies to all number sliders
> 
>  app.bar.mov

* In app bar, if I try removing `collapsedHeight` or `expandedHeight`, somehow the app bar starts misbehaving - same is happened in the showcase demo .
 * the `animationDuration` prop does not allow me to clear it — if I attempt to delete everything in the field, it will yield `0`' - I removed this logic trying to add undefined but need some more cleanup. We can fix this in another issue.

**Comment by ektasawant** [comment]
> > * In app bar, if I try removing `collapsedHeight` or `expandedHeight`, somehow the app bar starts misbehaving
> > * the `animationDuration` prop does not allow me to clear it — if I attempt to delete everything in the field, it will yield `0`'
> >   
> >   * This applies to all number sliders
> > 
> > app.bar.mov
> 
> * In app bar, if I try removing `collapsedHeight` or `expandedHeight`, somehow the app bar starts misbehaving - same is happened in the showcase demo . This should be fix in component library. For time being we can pass default value similar to this 

                        `collapsedHeight={appBarProps.collapsedHeight ? '' : 64 }
                        expandedHeight={appBarProps.expandedHeight ? '' : 200}`
> * the `animationDuration` prop does not allow me to clear it — if I attempt to delete everything in the field, it will yield `0`' - I removed this logic trying to add undefined but need some more cleanup. We can fix this in another issue.

**Comment by huayunh** [comment]
> In app bar, if I try removing `collapsedHeight` or `expandedHeight`, somehow the app bar starts misbehaving - same is happened in the showcase demo. This should be fixed in component library. 

Can you log an issue, if it is related to the component itself? 

Can you push the latest code, if more fixes have been made?

**Comment by ektasawant** [comment]
> > In app bar, if I try removing `collapsedHeight` or `expandedHeight`, somehow the app bar starts misbehaving - same is happened in the showcase demo. This should be fixed in component library.
> 
> Can you log an issue, if it is related to the component itself?
> 
> Can you push the latest code, if more fixes have been made?

- Fixed for docs https://github.com/brightlayer-ui/react-component-library/pull/565/commits/a043de8b64d2fcf4aa8432656288243d6d75db4d

**Review by huayunh — APPROVED** [review]
Hmm... It looks like the component magically fixed itself in the latest firebase deploy. I don't know why, but everything works well now. Thank you.

**Comment by ektasawant** [comment]
> Hmm... It looks like the component magically fixed itself in the latest firebase deploy. I don't know why, but everything works well now. Thank you.

@huayunh  This is because of https://github.com/brightlayer-ui/react-component-library/commit/a043de8b64d2fcf4aa8432656288243d6d75db4d . I have fixed this in dev docs repo and logged an issue for component library https://github.com/brightlayer-ui/react-component-library/issues/591

**Pull request merged**
