### PR TITLE
Feature/3315 drawer nav item api docs

### PR DESCRIPTION
**Pull request by ektasawant**
Fixes 3315 .

#### Changes proposed in this Pull Request:
- drawer nav item api doc
- stylesheet PR https://github.com/brightlayer-ui/react-component-library/pull/471 will fix mdx styling.
- 

#### To Test:
- http://localhost:3000/components/drawer/drawer-nav-item/api-docs

### CODE REVIEW

**Comment by huayunh** [comment]
- The commit history of this PR looks very long. Next time please make sure that you are checking out from the correct branch at the latest version.
- Same comment as https://github.com/brightlayer-ui/react-component-library/pull/474#issuecomment-1208271932 
- We should not be forcing people to click on the "sharedProps" link to view sharedProps, but instead list them out explicitly. I am not sure if that is within the scope of this story or not.
- The "Tips" section on the bottom would fit well as an example. I know this is out of the scope for this PR, but just some thoughts for the future.

**Comment by emclaug2** [comment]
I'm assuming this should be merged into release/dev-docs and not dev.  That'd fix the long commit history.

**Comment by ektasawant** [comment]
> I'm assuming this should be merged into release/dev-docs and not dev. That'd fix the long commit history.

changed the base branch.

**Comment by ektasawant** [comment]
Hi @huayunh ,
for below comments:
We should not be forcing people to click on the "sharedProps" link to view sharedProps, but instead list them out explicitly. I am not sure if that is within the scope of this story or not. - As per discussion current implementation is fine. But will check with you and team again and create new story for it.
The "Tips" section on the bottom would fit well as an example. I know this is out of the scope for this PR, but just some thoughts for the future. - made an feature request to add an example in drawer nav item. [478](https://github.com/brightlayer-ui/react-component-library/issues/478)

**Review by bkarambe — COMMENTED** [review]
Please remove drawer nav item from Drawer.mdx
Plese resolve merge conflicts

**Review by huayunh — APPROVED** [review]
Sounds good. Just clean up the style now that #471 has been merged and resolve conflicts like Suraj said above, and you are good to go

**Comment by ektasawant** [comment]
> Please remove drawer nav item from Drawer.mdx Plese resolve merge conflicts

done please review.

**Pull request merged**
