### PR TITLE
Feature/3409 update docs folder

### PR DESCRIPTION
**Pull request by ektasawant**
Fixes 3409 .

#### Changes proposed in this Pull Request:
- Update folder names, file names
- Put markdown, examples, data, playground in each component's folder
- Update eslint and prettier to use BLUI eslint and prettier package

#### To Test:
- Test all pages. All pages should work properly.

### CODE REVIEW

**Comment by huayunh** [comment]
- Fix that error pointed out in CI
- Why is there still a `docs/src/markdown` folder? Shouldn't all content be collected inside their corresponding component folders?
- I would put `docs/src/componentDocs/Drawer/data/DrawerTypes.tsx` inside `docs/src/componentDocs/Drawer/playground`
- There are two different things under the name "Component Preview": `docs/src/componentDocs/Drawer/playground/ComponentPreview.tsx` and `docs/src/pages/componentPreviewPage.tsx`. We may want to find a better name to describe these...
- For things like `docs/src/componentDocs/DrawerNavItem/markdown/DrawerNavItem.mdx` and `docs/src/componentDocs/DrawerNavItem/markdown/DrawerNavItemExamples.mdx`, I would call the first one `APIDocs.mdx` and the second one `Examples.mdx`. Remember, the goal is so that if you come back 6 months later, you can still remember what each folder means
- Speaking of which, would you please make a story to update `docs/README.md` for future maintainers?

**Comment by ektasawant** [comment]
- [X] Fix that error pointed out in CI - **Done**
- [ ] Why is there still a docs/src/markdown folder? Shouldn't all content be collected inside their corresponding component folders? - **SharedProps.mdx and StyleOverridesGuide.md we are still using and those are shared. We can move it to shared/markdown folder if we want.**
- [X]  I would put docs/src/componentDocs/Drawer/data/DrawerTypes.tsx inside docs/src/componentDocs/Drawer/playground -  **Done**
- [X] There are two different things under the name "Component Preview": docs/src/componentDocs/Drawer/playground/ComponentPreview.tsx and docs/src/pages/componentPreviewPage.tsx. We may want to find a better name to describe these... - Done.
- [X] For things like docs/src/componentDocs/DrawerNavItem/markdown/DrawerNavItem.mdx and docs/src/componentDocs/DrawerNavItem/markdown/DrawerNavItemExamples.mdx, I would call the first one APIDocs.mdx and the second one Examples.mdx. Remember, the goal is so that if you come back 6 months later, you can still remember what each folder means - Done
- [] Speaking of which, would you please make a story to update docs/README.md for future maintainers? Like documenting file hierarchies, similar to how the current docit readme is done. - sure will create one story for this once we  are finalize with folder structure.

**Comment by ektasawant** [comment]
It will be great if we are able to merge this story today so that other stories which are interrelated can be start. Anything needs to update I will log an issue and fix it. I hope it should be fine :).

**Comment by huayunh** [comment]
> We can move it to shared/markdown folder if we want. 

Yeah that would be ideal

**Comment by huayunh** [comment]
For `docs/src/componentDocs/Drawer/playground/data/DrawerTypes.tsx`: if there will be only one file then we shouldn't need to create a folder for it.

**Comment by huayunh** [comment]
Everything else looks good to me. You can merge this in after you make the changes mentioned above.

**Comment by ektasawant** [comment]
> Everything else looks good to me. You can merge this in after you make the changes mentioned above.

Done. Merging this story.

**Pull request merged**
