### PR TITLE
playground for App Bar

### PR DESCRIPTION
**Pull request by ektasawant**
Fixes 3404 .

#### Changes proposed in this Pull Request:
- Added basic playground for App Bar with all props of App Bar

#### To Test:
- /components/app-bar/playground

### CODE REVIEW

**Comment by huayunh** [comment]
When `animationDuration` is set to `1000` and only `1000`, the app bar refuses to expand. All other numbers work just fine.

https://user-images.githubusercontent.com/8997218/189242294-034f3c4b-7365-4896-aa66-e4d1c6a94b2f.mov

I love how you used a disabled text field for `scrollContainerId`.

**Comment by ektasawant** [comment]
> When `animationDuration` is set to `1000` and only `1000`, the app bar refuses to expand. All other numbers work just fine.
> 
>  Screen.Recording.2022-09-08.at.7.19.38.PM.mov 
> I love how you used a disabled text field for `scrollContainerId`.

Working fine on my end for firebase URL. @daileytj / @emclaug2  / @jeffvg  please let me know if you are also facing the same issue as Huayun mentioned.
Sep-09-2022 11-23-26

**Comment by daileytj** [comment]
I'm having the same issue as Huayun with the scroll issue with the `animationDuration` being set to 1000. It will occasionally open back up if I scroll up and down, but it's inconsistent.

**Comment by ektasawant** [comment]
> I'm having the same issue as Huayun with the scroll issue with the `animationDuration` being set to 1000. It will occasionally open back up if I scroll up and down, but it's inconsistent.

This issue occurs when we scroll the page fast. Same issue I can see in the storybook.

**Comment by daileytj** [comment]
> > I'm having the same issue as Huayun with the scroll issue with the `animationDuration` being set to 1000. It will occasionally open back up if I scroll up and down, but it's inconsistent.
> 
> This issue occurs when we scroll the page fast. Same issue I can see in the storybook.

Sounds good. I'll approve this, but be sure to write up an issue to address this.

**Review by daileytj — APPROVED** [review]

**Review by jeffvg — APPROVED** [review]
I see the same as everyone with ```animationDuration```  set to 1000. It seems to be more noticed on firefox browser. This can be merged once issue is opened

**Comment by ektasawant** [comment]
> > > I'm having the same issue as Huayun with the scroll issue with the `animationDuration` being set to 1000. It will occasionally open back up if I scroll up and down, but it's inconsistent.
> > 
> > 
> > This issue occurs when we scroll the page fast. Same issue I can see in the storybook.
> 
> Sounds good. I'll approve this, but be sure to write up an issue to address this.

Logged an issue https://github.com/brightlayer-ui/react-component-library/issues/515

**Pull request merged**
