### PR TITLE
Feature/3519 spacer playground

### PR DESCRIPTION
**Pull request by ektasawant**
Fixes 3519 .

#### Changes proposed in this Pull Request:
- Playground for Spacer
- 
- 

#### To Test:
- /components/spacer/playground

### CODE REVIEW

**Comment by emclaug2** [comment]
Hey Ekta we talked with Joe in office hours today and we think in its current state, this playground is confusing for users to fully understand what's happening.  We also think that this content would be better suited on the Examples page.

I would recommend commenting out the playground in case we want to revisit this in the future & the examples page can be implemented as a separate story.

**Comment by huayunh** [comment]
Thank you for the experimentation here though. What you did here fostered some good discussion during PM office hour and provided us a lot of insights on how we should present the content to our users.

**Comment by ektasawant** [comment]
Sure will hide the playground tab for spacer .

**Comment by ektasawant** [comment]
> Sure will hide the playground tab for the spacer.

Hid the playground tab https://github.com/brightlayer-ui/react-component-library/pull/537/commits/9264f82051432f37f74ca286038096705f5c81a9

**Comment by ektasawant** [comment]
Merging this branch with the playground tab of the spacer hidden.

**Pull request merged**
