### PR TITLE
fix activeItemIconColor and activeItemFontColor prop

### PR DESCRIPTION
**Pull request by ektasawant**
Fixes 3543 .

#### Changes proposed in this Pull Request:
- https://github.com/brightlayer-ui/react-component-library/issues/527 
- 
- 

#### Screenshots:
Screenshot 2022-09-28 at 5 07 40 PM

#### To Test:
- http://localhost:3001/components/drawer-rail-item/playground

**Note: Note sure whether library changes will updated in firebase URL. Need to check locally .**

### CODE REVIEW

**Comment by jeffvg** [comment]
this is not working for me locally or on firebase


https://user-images.githubusercontent.com/37150565/192832273-d8457dea-45f1-4da6-bac4-a26fb899ab0e.mov

**Comment by ektasawant** [comment]
> this is not working for me locally or on firebase
> 
>  rail-shared-props.mov

Can you try to copy dist folder of `react-component-library` to `docs/node_modules/@brightlayer-ui/react-components` ? 
I need to copy and paste manually for react-dev docs.

**Comment by jeffvg** [comment]
> 

copied over the dist and is working but we still have these console warnings.

image

**Comment by ektasawant** [comment]
> remove transparent color

https://github.com/brightlayer-ui/react-component-library/pull/556/commits/57994f083be3a8c6669d23ca63a22355d629043b this change will fix mentioned warning.

**Review by jeffvg — APPROVED** [review]
changes look good, no console warnings

**Comment by daileytj** [comment]
> > this is not working for me locally or on firebase
> > rail-shared-props.mov
> 
> Can you try to copy dist folder of `react-component-library` to `docs/node_modules/@brightlayer-ui/react-components` ? I need to copy and paste manually for react-dev docs.

Does this "copying the dist folder" need to happen every time? If so, is there an issue to write a script to deal with this?

**Pull request merged**
