### PR TITLE
Feature/3552 markdown fixes dev docs

### PR DESCRIPTION
**Pull request by bkarambe**
Fixes # BLUI-3552

#### Changes proposed in this Pull Request:
- Added border radius to snippet 
- Updated description for examples

#### Screenshots:
Screenshot 2022-10-28 at 6 41 09 PM

#### To Test:
- yarn start:reactdev

### CODE REVIEW

**Comment by emclaug2** [comment]
Going through the docs now, noticed one discrepancy between the two drawers; can you update react (right) drawer nav item order to match angular (left) ?  Also react is missing the hierarchical styles. 

image

**Comment by emclaug2** [comment]
It seems the content of the Drawer page needs to be updated to match angular as well.  On the drawer page, there should be a links to the each subsection.

**Comment by jeffvg** [comment]
The interactive subheader example slightly different than the angular example. The add new org item shouldn't be selectable here...

image

**Comment by bkarambe** [comment]
> The interactive subheader example slightly different than the angular example. The add new org item shouldn't be selectable here...
> 
> image

Yes. That we will be covering in the following cleanup ticket

**Comment by emclaug2** [comment]
There's a weird overflow behavior happening on the Condensed Drawer Rail Item example.

image

There's also some instances of where the code highlighting is off by 1 line, but I'm making a fix for that right now.

**Review by emclaug2 — APPROVED** [review]

**Review by emclaug2 — APPROVED** [review]

**Pull request merged**
