### PR TITLE
Updated Drawer comp to work with mui v5 style engine and updated docs

### PR DESCRIPTION
**Pull request by bkarambe**
Fixes #BLUI-3121

Changes proposed in this Pull Request:
Update styles to use Mui-v5 Styled components
Update component to extend sx prop

Test:
There is a showcase branch feature/3050-channel-value-mui-v5-styles-update that you can use to test this.
When testing, ensure that there are no breaking changes and that the old API properties still work the same and that you can still style things with inline styles as well as using our classes prop.
Also, test out the new sx prop extension. You can apply styles to the root by using sx directly on the component as well as by targeting nested items by the generated classnames.

### CODE REVIEW

**Comment by emclaug2** [comment]
> DrawerFooter

I'm guessing this PR is for the top-level Drawer and not DrawerFooter right?

**Comment by bkarambe** [comment]
> > DrawerFooter
> 
> I'm guessing this PR is for the top-level Drawer and not DrawerFooter right?

Yes it is for top level Drawer comp

**Review by jeffvg — APPROVED** [review]
seems ok to me. Just need to update the doc for .BluiDrawer-expanded @emclaug2

**Comment by daileytj** [comment]
sideBorder default styles and sx overrides are broken. Here's the result of adding these styles
`sideBorder={true}
  sx={{ '& .BluiDrawer-sideBorder': { width: '40px', backgroundColor: 'orange' } }}`


Screen Shot 2022-05-18 at 11 38 31 AM

**Comment by jeffvg** [comment]
> sideBorder default styles and sx overrides are broken. Here's the result of adding these styles `sideBorder={true} sx={{ '& .BluiDrawer-sideBorder': { width: '40px', backgroundColor: 'orange' } }}`
> 
> Screen Shot 2022-05-18 at 11 38 31 AM

strang that looks diff than what I saw yesterday, I was using something like '& .BluiDrawer-sideBorder': { p: '24px', backgroundColor: 'green' } and had this...

image

**Comment by daileytj** [comment]
hmmm... interesting @jeffvg. I'll try a fresh clone one more time just to be sure.

**Comment by daileytj** [comment]
I tried on a fresh clone multiple times now with no luck on resolving the issue I have.

**Comment by emclaug2** [comment]
@daileytj Here's what I see using your code snippet from above: 
image

**Comment by bkarambe** [comment]
> sx={{ '& .BluiDrawer-sideBorder': { width: '40px', backgroundColor: 'orange' } }}

I tried by checking out dev branches on both comp lib and showcase. Applied these changes, but found the same result :
`sideBorder={true}
 classes={{sideBorder: classes.sideborder}}`

```
   sideborder: {
        width: '40px',
        backgroundColor: 'orange'
    }
```

Here's the screenshot after applying these changes :
MicrosoftTeams-image (5)

**Review by daileytj — APPROVED** [review]

**Pull request merged**
