### PR TITLE
Feature/3424 example page for hero

### PR DESCRIPTION
**Pull request by ektasawant**
Fixes 3424 .

#### Changes proposed in this Pull Request:
- Added examples for the Hero component
- 
- 

#### To Test:
- /components/hero/examples

### CODE REVIEW

**Comment by emclaug2** [comment]
For the "Hero with Icon Size and Image Types" example the code snippet is very, very long.  Can you iterate over an array instead of declaratively writing all these Heroes to save remove 2/3 of the lines from this example?

**Comment by ektasawant** [comment]
> For the "Hero with Icon Size and Image Types" example the code snippet is very, very long. Can you iterate over an array instead of declaratively writing all these Heroes to save remove 2/3 of the lines from this example?

Done

**Comment by ektasawant** [comment]
> image image image
> 
> Make sure to add a code highlight to these props.
> 
> The HeroBanner doesn't accept up to 4 Heroes as a hard limit, it's just by default. Potential reword: `The <HeroBanner /> component is a simple wrapper component that accepts <Hero /> components as its children`

Done 👍

**Comment by huayunh** [comment]
- [ ] I would recommend turning on the `divider` in the "Heroes with a Hero Banner" example
- [ ] Same example, I would set `unitSpacing` of the first Hero to `"hide"`
- [ ] in the "Hero with Value and Units" example, there is the sentence "It is used to commonly display metric data". Can you reword this? "It is **commonly** used to ..."

**Comment by huayunh** [comment]
everything else looking great!

**Comment by ektasawant** [comment]
> everything else looking great!

Fix [List](https://github.com/brightlayer-ui/react-component-library/pull/525#issuecomment-1247543701) in this PR

**Comment by huayunh** [comment]
> > everything else looking great!
> 
> Fix [List](https://github.com/brightlayer-ui/react-component-library/pull/525#issuecomment-1247543701) in this PR

You may want to read that sentence again word-by-word

**Comment by ektasawant** [comment]
@everyone Is it good to merge ?

**Comment by huayunh** [comment]
Looks good to me

**Pull request merged**
