### PR TITLE
Feature/3552 remove style overrides name quotes

### PR DESCRIPTION
**Pull request by bkarambe**
Fixes # BLUI-3552

#### Changes proposed in this Pull Request:
API Docs
In the 'style overrides' section, the Name should not be in a code block (second bullet)
Do we need to update the 'any other props will be provided to the root component' to Box instead of div? I'm pretty sure in the MUI 5 we converted everything to use box.
All tables should be 100% width

#### Screenshots:
Screenshot 2022-10-06 at 2 41 53 PM

#### To Test:
- yarn strat:reactdev

### CODE REVIEW

**Comment by emclaug2** [comment]
@bkarambe Can you please resolve these merge conflicts?

**Comment by emclaug2** [comment]
Also see your other PR for the CI github deploy fix.

The summary is that Firebase pushed out a buggy package & this change manually sets the firebase cli version instead of using latest.

**Comment by huayunh** [comment]
why does the drawer layout API doc table look so different from other API tables?

**Comment by huayunh** [comment]
Somehow, when I navigate to Toolbar Menu Examples page, there is a console warning. I don't know if this is caused by this PR or not.

```
Warning: validateDOMNesting(...): <p> cannot appear as a descendant of <p>.
```

**Comment by bkarambe** [comment]
> Somehow, when I navigate to Toolbar Menu Examples page, there is a console warning. I don't know if this is caused by this PR or not.
> 
> ```
> Warning: validateDOMNesting(...): <p> cannot appear as a descendant of <p>.
> ```

Logged an issue https://github.com/brightlayer-ui/react-component-library/issues/586

**Comment by bkarambe** [comment]
> why does the drawer layout API doc table look so different from other API tables?

Good catch @huayunh . There were some styles applied to table long back. Removed now.

**Pull request merged**
