### PR TITLE
Feature/3028 appbar mui5 styles

### PR DESCRIPTION
**Pull request by emclaug2**
#### Changes proposed in this Pull Request:
- AppBar now MUI5 style engine

### CODE REVIEW

**Comment by daileytj** [comment]
Can you update the submodule pointer to point back to dev?

**Comment by daileytj** [comment]
@emclaug2 I hope you don't mind my pushing directly to your branch. It was just the className pass-through prop missing so className style overrides weren't working.

**Review by daileytj — APPROVED** [review]

**Comment by daileytj** [comment]
I know I told you to point this at dev, but you end up needing to install @emotion/css. We may want to make a showcase update adding @emotion/css as a dependency that we can point at.

**Comment by emclaug2** [comment]
> I know I told you to point this at dev, but you end up needing to install @emotion/css. We may want to make a showcase update adding @emotion/css as a dependency that we can point at.

I've opened up another PR for showcase demo; after that gets merged in we can update the pointer here again to fix the demo.

**Pull request merged**
