### PR TITLE
Added Drawer Nav Group api docs

### PR DESCRIPTION
**Pull request by bkarambe**
Fixes # BLUI-3314

#### Changes proposed in this Pull Request:
- Added Drawer Nav Group api docs

#### Screenshots:
Screenshot 2022-07-28 at 4 56 32 PM

#### To Test:
- yarn start:reactdev
- Navigate to Drawer->Drawer Nav Group->API DOCS (tab)

**Note: - DO NOT MERGE until #468 gets merged**

### CODE REVIEW

**Review by jeffvg — APPROVED** [review]
looks good

**Comment by jeffvg** [comment]
> looks good but to keep naming conventions the same should DrawerNavGroup.mdx file be named DrawerNavGroupMarkdown.mdx?

Noticed shared props link not working here, when will drawer shared props be linked in?

**Comment by bkarambe** [comment]
> > looks good but to keep naming conventions the same should DrawerNavGroup.mdx file be named DrawerNavGroupMarkdown.mdx?
> 
> Noticed shared props link not working here, when will drawer shared props be linked in? Thinking this could be a component with its own markdown and used where needed

@jeffvg @daileytj @joebochill  Do we need to add Shared Props section in each mdx file?

**Comment by joebochill** [comment]
The shared props should be shown for each component, but we should not be copy/pasting them. They should be defined once in a way that is reusable in each page.

**Comment by bkarambe** [comment]
> The shared props should be shown for each component, but we should not be copy/pasting them. They should be defined once in a way that is reusable in each page.

Added SharedProps.mdx and using it as a common.

**Pull request merged**
