### PR TITLE
Added line highliting to the drawer nav item examples

### PR DESCRIPTION
**Pull request by bkarambe**
Fixes # BLUI-3324

#### Changes proposed in this Pull Request:
- Added line highlighting the code snippet examples

#### Screenshots:
Screenshot 2022-08-05 at 5 35 01 PM

#### To Test:
- yarn start:reactdev
- Navigate to Drawer->Drawer Nav Item

### CODE REVIEW

**Comment by bkarambe** [comment]
_Warning
(29:3) autoprefixer: Replace color-adjust to print-color-adjust. The color-adjust shorthand is currently deprecated.


error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Exited with code exit status 1_


Getting this warning, which is causing the circle  CI to fail. prismjs plugin is internally using that dependency. I tried installing the specific version, but it still uses the version which was introduced in prismjs plugin

**Review by huayunh — APPROVED** [review]
I don't know much about CI. Code change looks good to me. Can verify it spins properly on localhost.

**Comment by emclaug2** [comment]
@bkarambe Looking at the circleci output, warnings will cause errors in CI.  `cd docs && yarn build` generates this warning:

```

Compiled with warnings.

Warning
(29:3) autoprefixer: Replace color-adjust to print-color-adjust. The color-adjust shorthand is currently deprecated.
```

Address the warning above & you should be fine.

**Comment by huayunh** [comment]
@emclaug2 the `autoprefixer` is a dependency of `prismjs` only, which we have no control over. And we are already using the latest version of `prismjs`. What's the best way to address this deprecation issue?

**Comment by emclaug2** [comment]
> @emclaug2 the `autoprefixer` is a dependency of `prismjs` only, which we have no control over. And we are already using the latest version of `prismjs`. What's the best way to address this deprecation issue?

https://github.com/twbs/bootstrap/issues/36259

Add to docs/package.json
```
"resolutions": {
    "autoprefixer": "10.4.5"
}
```

Run `yarn` to get a new lock file & it's good to go.

**Comment by bkarambe** [comment]
> > @emclaug2 the `autoprefixer` is a dependency of `prismjs` only, which we have no control over. And we are already using the latest version of `prismjs`. What's the best way to address this deprecation issue?
> 
> [twbs/bootstrap#36259](https://github.com/twbs/bootstrap/issues/36259)
> 
> Add to docs/package.json
> 
> ```
> "resolutions": {
>     "autoprefixer": "10.4.5"
> }
> ```
> 
> Run `yarn` to get a new lock file & it's good to go.

Done. Thanks @emclaug2

**Comment by huayunh** [comment]
Evan you rock!

**Pull request merged**
